apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: alitunckasik/phonebook-bronze-app-result
        name: resultserver
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
